name: Deploy Frappe App

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup StrongDM Access
        uses: strongdm/sdm-access-gh-action@v1.0.2
        with:
          admin-token: ${{ secrets.SDM_ADMIN_TOKEN }}

      - name: Test StrongDM CLI Connection
        run: |
          sdm status

      - name: Deploy to customer1
        if: contains(github.event.head_commit.message, '[customer1]')
        run: |
          sdm ssh erp_demo "
            cd /opt/bench/frappe-bench/ &&
            bench get-app git@github.com:oun-qa/malek_app.git
          "
