name: StrongDM Workflow

on:
  workflow_dispatch:

jobs:
  setup-strongdm:
    runs-on: ubuntu-latest

    env:
      SDM_DOCKERIZED: true
      SDM_VERBOSE: true
      SDM_DISABLE_UPDATE: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download StrongDM CLI
        run: |
          curl -Lso sdm.zip "https://app.strongdm.com/releases/cli/linux/oun-for-consultation-and-support"
          unzip sdm.zip
          rm sdm.zip
          chmod +x sdm

      - name: StrongDM install
        run: |
          sudo ./sdm install --nologin

      - name: Test StrongDM CLI
        run: |
          sdm login --admin-token=${{ secrets.SDM_ADMIN_TOKEN }}
          sdm status
          # cat /var/tmp/sdm.log

      - name: Connect and deploy (Customer 1)
        # if: contains(github.event.head_commit.message, '[customer1]')
        run: |
          sdm connect erp_demo
          until sdm ready erp_demo; do sleep 1; echo "checking if resource is ready"; done
          sdm status
          
          mkdir -p ~/.ssh
          echo "[127.0.0.1]:10002 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDzwkDVsJY0Hf9injNAIkmzfAwU76fWVuF4rpa0dXut7fJqHQBBmrGENcTvuogWa5pa4E/tYry1DCGp6tefz+fJpmUNh2PJ2z0Js/TK1WWiP3Dd99Y4wNGahah/sqFkQrDxmJ7tTqPmhMV9fQyCM4e8+2zh1QbkJroZMEkSI/UzSQ==" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
          sdm ssh erp_demo "
            set -e
            # Manually set PATH to include Frappe Bench's bin directory
            export PATH="/opt/bench/frappe-bench/env/bin:$PATH"
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            cd /opt/bench/frappe-bench/
            git config --global url.\"https://github.com/\".insteadOf git@github.com:
            bench get-app https://github.com/oun-qa/malek_app.git
          "
