name: Deploy Frappe App

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download StrongDM CLI (Linux amd64)
        run: |
          curl -L https://app.strongdm.com/releases/cli/strongdm-cli_latest_linux_amd64.zip -o sdm.zip
          unzip sdm.zip
          chmod +x sdm
          sudo mv sdm /usr/local/bin/sdm
        env:
          SDM_ADMIN_TOKEN: ${{ secrets.SDM_ADMIN_TOKEN }}

      - name: Deploy to customer1
        if: contains(github.event.head_commit.message, '[customer1]')
        run: |
          SDM_ADMIN_TOKEN=${{ secrets.SDM_ADMIN_TOKEN }} sdm ssh erp_demo "
            cd /opt/bench/frappe-bench/ &&
            bench get-app git@github.com:oun-qa/malek_app.git
          "
